server {
    listen 80;

    location / {
        proxy_pass http://web-server-service.task1.svc.cluster.local;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
