apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: task1
  labels:
    app: web-server
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80

  type: NodePort
