apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: week2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-logs
        hostPath:
          path: /var/log/nginx
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: week2
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80