apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  namespace: task15
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: pushgateway
  endpoints:
    - port: metrics
