apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-alert
  namespace: task15
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: discord
    matchers:
      - name: alertname
        value: ContainerHighCPU
  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            key: url
            name: discord-webhook
          sendResolved: true
