server {
    listen 80;

    location / {
        proxy_pass http://web-server-service.week2.svc.cluster.local:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
