apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-metrics-app
  namespace: task15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-metrics-app
  template:
    metadata:
      labels:
        app: my-metrics-app
    spec:
      containers:
        - name: my-metrics-app
          image: vup4k0806/my-metrics-app:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-metrics-app
  namespace: task15
  labels:
    app: my-metrics-app
spec:
  selector:
    app: my-metrics-app
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
